### ISSUE TITLE
Doc in /JungleBus/Configuration/ReceiveConfigurationExtensions.cs doesn't match methods

### ISSUE THREAD

**Issue by neilfitzgerald** [rfleming71/JungleBus#12]
Notice some doc comments + exception messages in /JungleBus/Configuration/ReceiveConfigurationExtensions.cs that don't match the methods. Its trivial changes - I've attached some suggested changes in the attached zip.

Most of the change is for method SetNumberOfPollingInstances

[ReceiveConfigurationExtensions.zip](https://github.com/rfleming71/JungleBus/files/996873/ReceiveConfigurationExtensions.zip)

**Comment by neilfitzgerald** [comment]
Sent you a pull request

**Comment by rfleming71** [comment]
Merged with PR #13
